// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://cqirxskgwmniwulavkkw.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxaXJ4c2tnd21uaXd1bGF2a2t3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE5NjAyMTAsImV4cCI6MjA0NzUzNjIxMH0.cw7bQ04TIdj6z1c9UEMm67f45y75UAwdqwa46p1EN9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);